spring.application.name=cms

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cms_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:yourmail@gmail.com}
spring.mail.password=${MAIL_PASSWORD:yourpassword}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Logging
spring.mail.properties.mail.debug=false
logging.level.org.springframework.mail=ERROR